insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (1, 'Gazelle, grant''s', 'Armenian', '23.05.2016');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (2, 'Pine siskin', 'Hiri Motu', '25.08.1997');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (3, 'Common turkey', 'Danish', '26.02.1996');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (4, 'Kangaroo, jungle', 'Kurdish', '17.01.2014');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (5, 'Crab, red lava', 'Bengali', '22.07.2015');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (6, 'Vulture, king', 'Japanese', '15.09.1960');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (7, 'Red brocket', 'Malayalam', '25.04.1999');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (8, 'Golden jackal', 'Azeri', '04.11.1980');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (9, 'Brush-tailed rat kangaroo', 'Belarusian', '27.01.1984');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (10, 'Jackal, golden', 'Nepali', '31.01.1978');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (11, 'Grizzly bear', 'Burmese', '25.02.1980');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (12, 'Snake, buttermilk', 'Catalan', '13.04.2010');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (13, 'Two-toed tree sloth', 'Burmese', '27.01.1996');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (14, 'Pale-throated three-toed sloth', 'Oriya', '22.12.1978');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (15, 'Common long-nosed armadillo', 'Gujarati', '04.03.2017');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (16, 'Quoll, spotted-tailed', 'Aymara', '25.08.1950');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (17, 'Penguin, magellanic', 'Armenian', '22.08.1972');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (18, 'North American porcupine', 'Dutch', '07.11.1995');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (19, 'Wildebeest, blue', 'New Zealand Sign Language', '28.08.2011');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (20, 'Macaw, blue and yellow', 'Persian', '01.07.1956');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (21, 'Mallard', 'Tsonga', '23.11.2000');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (22, 'Green-backed heron', 'Japanese', '04.11.1984');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (23, 'Collared lemming', 'Swedish', '20.04.1961');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (24, 'Tamandua, southern', 'Burmese', '28.08.2006');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (25, 'Owl, white-browed', 'Haitian Creole', '22.11.2002');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (26, 'Pheasant, ring-necked', 'Ndebele', '13.01.1951');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (27, 'Wolf, common', 'Somali', '09.02.1970');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (28, 'Sarus crane', 'Swedish', '17.08.1995');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (29, 'Eagle, white-bellied sea', 'Assamese', '26.09.1992');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (30, 'Chuckwalla', 'Persian', '13.07.1957');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (31, 'Canada goose', 'Bosnian', '16.08.1988');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (32, 'Currasow (unidentified)', 'Dzongkha', '12.04.1985');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (33, 'Macaque, rhesus', 'Indonesian', '26.06.1973');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (34, 'Crested bunting', 'Polish', '10.10.1958');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (35, 'Blue-faced booby', 'Albanian', '24.08.2016');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (36, 'Little cormorant', 'Tswana', '17.11.1991');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (37, 'Rhesus monkey', 'Dzongkha', '16.12.1972');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (38, 'Magpie, australian', 'Armenian', '15.10.1953');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (39, 'Rhinoceros, white', 'Icelandic', '06.11.2000');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (40, 'Moose', 'Tsonga', '22.01.2013');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (41, 'Dragon, frilled', 'Yiddish', '09.02.2002');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (42, 'Pine siskin', 'Lao', '19.10.1968');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (43, 'Australian spiny anteater', 'Dhivehi', '15.09.2017');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (44, 'Lynx, african', 'Chinese', '18.07.1996');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (45, 'Rhinoceros, white', 'Oriya', '29.06.1968');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (46, 'Eagle, bald', 'Quechua', '01.09.2006');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (47, 'Cape clawless otter', 'New Zealand Sign Language', '18.06.2004');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (48, 'Bulbul, african red-eyed', 'Oriya', '06.05.1953');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (49, 'Screamer, crested', 'Zulu', '30.07.2007');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (50, 'Eagle, bald', 'Zulu', '30.06.2005');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (51, 'Mississippi alligator', 'Kurdish', '03.06.1952');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (52, 'Eagle, long-crested hawk', 'Malayalam', '17.04.2008');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (53, 'Lemming, collared', 'Montenegrin', '09.02.1987');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (54, 'Snake-necked turtle', 'Māori', '02.03.2012');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (55, 'Great horned owl', 'Marathi', '27.12.1977');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (56, 'Sifaka, verreaux''s', 'Quechua', '23.01.1962');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (57, 'Hornbill, leadbeateri''s ground', 'Tajik', '10.08.1979');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (58, 'Violet-crested turaco', 'Belarusian', '04.04.1961');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (59, 'Woodpecker, downy', 'Belarusian', '21.04.1997');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (60, 'Gecko, barking', 'Lao', '28.12.1955');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (61, 'Flycatcher, tyrant', 'Kashmiri', '16.07.2013');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (62, 'Mynah, common', 'Chinese', '26.10.1957');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (63, 'Golden-mantled ground squirrel', 'Tetum', '19.03.1995');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (64, 'Wombat, southern hairy-nosed', 'Marathi', '10.07.2003');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (65, 'Lark, horned', 'Kazakh', '24.04.1998');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (66, 'White-headed vulture', 'Gujarati', '30.10.1974');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (67, 'Arctic hare', 'Belarusian', '13.09.1976');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (68, 'Boar, wild', 'Gagauz', '25.04.2002');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (69, 'Kori bustard', 'Irish Gaelic', '28.02.1990');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (70, 'Stilt, black-winged', 'Montenegrin', '22.11.1997');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (71, 'Lemming, collared', 'Kashmiri', '27.06.1988');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (72, 'Galapagos dove', 'French', '05.03.1994');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (73, 'American Virginia opossum', 'Thai', '12.11.1950');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (74, 'Creeper, black-tailed tree', 'Hungarian', '25.03.2005');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (75, 'Small-clawed otter', 'Fijian', '22.11.1969');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (76, 'Spotted-tailed quoll', 'Pashto', '08.11.1968');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (77, 'Water monitor', 'Hiri Motu', '30.03.1998');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (78, 'Barrows goldeneye', 'Assamese', '13.07.1995');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (79, 'Crane, blue', 'Maltese', '15.04.1995');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (80, 'Yellow-rumped siskin', 'Zulu', '02.10.2011');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (81, 'Black-necked stork', 'Polish', '10.11.1951');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (82, 'Malabar squirrel', 'Tamil', '09.07.1967');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (83, 'Common zorro', 'Irish Gaelic', '09.07.1989');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (84, 'Small-clawed otter', 'Kazakh', '08.10.1956');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (85, 'Dove, rock', 'Polish', '03.10.2006');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (86, 'Large-eared bushbaby', 'Polish', '31.08.1958');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (87, 'Squirrel, pine', 'Luxembourgish', '17.06.1987');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (88, 'Monkey, bleeding heart', 'Punjabi', '01.01.2016');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (89, 'Sage hen', 'Tok Pisin', '02.01.1988');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (90, 'Dog, black-tailed prairie', 'Romanian', '02.02.1965');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (91, 'Phalarope, northern', 'Gujarati', '29.08.1984');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (92, 'Black-tailed deer', 'Catalan', '26.01.1970');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (93, 'Kongoni', 'Swedish', '29.07.1974');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (94, 'North American red fox', 'Albanian', '04.06.2005');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (95, 'Sandhill crane', 'French', '14.11.2014');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (96, 'Phalarope, red-necked', 'Tsonga', '03.03.2014');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (97, 'Dragon, ornate rock', 'Italian', '11.11.1959');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (98, 'Cat, tiger', 'Dzongkha', '29.05.1975');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (99, 'Emerald green tree boa', 'Khmer', '21.01.2017');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (100, 'Possum, common brushtail', 'Zulu', '14.10.2002');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (101, 'Macaque, bonnet', 'Afrikaans', '24.07.1951');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (102, 'Heron, green', 'Montenegrin', '10.05.1989');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (103, 'Wombat, common', 'Belarusian', '11.10.2008');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (104, 'Bat, little brown', 'Albanian', '18.04.2008');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (105, 'Stork, openbill', 'Aymara', '23.05.1999');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (106, 'Hornbill, leadbeateri''s ground', 'Persian', '08.07.2015');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (107, 'Tropical buckeye butterfly', 'Polish', '03.12.1986');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (108, 'Stanley crane', 'Punjabi', '18.05.1965');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (109, 'Squirrel, arctic ground', 'Gagauz', '07.11.2005');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (110, 'Feathertail glider', 'Norwegian', '04.03.2004');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (111, 'Hoffman''s sloth', 'Lao', '16.12.1979');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (112, 'Python (unidentified)', 'German', '16.05.1977');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (113, 'Booby, masked', 'Punjabi', '04.03.2014');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (114, 'European wild cat', 'Georgian', '03.09.1969');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (115, 'Lory, rainbow', 'Arabic', '31.03.1954');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (116, 'Marmot, hoary', 'Bengali', '06.10.1951');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (117, 'Squirrel, thirteen-lined', 'Dutch', '12.11.2015');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (118, 'Yellow-throated sandgrouse', 'Somali', '23.04.2003');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (119, 'Eastern white pelican', 'Italian', '27.09.2009');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (120, 'White-tailed deer', 'Pashto', '24.04.1995');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (121, 'Greater kudu', 'Dari', '25.10.2003');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (122, 'Bohor reedbuck', 'Filipino', '08.08.1998');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (123, 'Woodchuck', 'Mongolian', '24.03.1973');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (124, 'Mandras tree shrew', 'Czech', '03.05.2005');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (125, 'Crane, blue', 'Kyrgyz', '11.12.2002');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (126, 'Savanna fox', 'Swahili', '17.01.1966');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (127, 'Vine snake (unidentified)', 'Danish', '16.09.1959');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (128, 'Kangaroo, brush-tailed rat', 'Czech', '31.03.1964');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (129, 'Kingfisher, white-throated', 'Hungarian', '30.12.1969');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (130, 'Weeper capuchin', 'Kannada', '28.04.2003');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (131, 'Skink, blue-tongued', 'Pashto', '10.04.2013');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (132, 'Indian mynah', 'New Zealand Sign Language', '14.12.1972');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (133, 'Yellow-headed caracara', 'Albanian', '16.09.1987');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (134, 'Gull, kelp', 'Swedish', '20.09.1985');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (135, 'Black-tailed tree creeper', 'Estonian', '10.06.1977');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (136, 'Tern, white-winged', 'Arabic', '04.08.2014');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (137, 'Snake, tiger', 'Gagauz', '06.11.2007');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (138, 'Caribou', 'Pashto', '04.08.1973');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (139, 'Goose, canada', 'Swati', '11.06.1988');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (140, 'Rose-ringed parakeet', 'Albanian', '02.12.1995');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (141, 'Squirrel, palm', 'Dhivehi', '29.05.1965');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (142, 'Bee-eater, carmine', 'Aymara', '06.07.2003');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (143, 'Kafue flats lechwe', 'English', '19.12.1957');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (144, 'Pied crow', 'Lithuanian', '06.07.1960');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (145, 'Pied avocet', 'Kashmiri', '26.05.2006');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (146, 'Dragon, frilled', 'Latvian', '12.10.1984');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (147, 'Tammar wallaby', 'Malagasy', '24.03.2000');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (148, 'Gull, lava', 'Ndebele', '14.10.1965');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (149, 'Western spotted skunk', 'Italian', '18.11.2013');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (150, 'American beaver', 'Norwegian', '23.05.1970');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (151, 'Black and white colobus', 'Swahili', '14.07.1970');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (152, 'European badger', 'Greek', '06.09.1987');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (153, 'Goldeneye, barrows', 'Romanian', '29.08.1960');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (154, 'Armadillo, seven-banded', 'Arabic', '03.07.1980');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (155, 'American Virginia opossum', 'Thai', '17.09.2011');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (156, 'American beaver', 'Dari', '02.04.1954');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (157, 'Dromedary camel', 'Persian', '25.07.2012');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (158, 'Tsessebe', 'Portuguese', '26.02.1994');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (159, 'American woodcock', 'Chinese', '20.08.2000');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (160, 'Australian sea lion', 'Kashmiri', '22.11.1971');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (161, 'Greater sage grouse', 'French', '04.08.2007');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (162, 'Oryx, beisa', 'Romanian', '18.10.2002');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (163, 'Crow, american', 'Romanian', '14.12.1958');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (164, 'Kangaroo, jungle', 'Dzongkha', '10.07.2016');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (165, 'White-eye, pale', 'Tswana', '06.02.1992');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (166, 'Goose, canada', 'Polish', '07.10.1958');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (167, 'Clark''s nutcracker', 'Pashto', '14.06.2017');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (168, 'Mule deer', 'Greek', '06.05.2005');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (169, 'Tailless tenrec', 'English', '25.01.1982');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (170, 'Kinkajou', 'Greek', '17.03.1982');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (171, 'Fox, arctic', 'Dutch', '14.06.1956');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (172, 'Dove, emerald-spotted wood', 'Pashto', '26.04.1978');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (173, 'Southern hairy-nosed wombat', 'Pashto', '25.08.1987');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (174, 'Sage hen', 'English', '09.11.1989');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (175, 'Galapagos sea lion', 'Icelandic', '08.12.1986');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (176, 'Silver-backed fox', 'Ndebele', '11.07.1989');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (177, 'Seal, common', 'Norwegian', '16.08.1989');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (178, 'Grey mouse lemur', 'Pashto', '22.01.2004');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (179, 'Dragon, western bearded', 'Norwegian', '19.05.1970');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (180, 'Tailless tenrec', 'Nepali', '12.02.1982');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (181, 'Neotropic cormorant', 'West Frisian', '11.04.1993');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (182, 'White-browed owl', 'West Frisian', '21.02.1999');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (183, 'Indian porcupine', 'Dzongkha', '04.10.1972');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (184, 'Bushbaby, large-eared', 'Norwegian', '11.08.1953');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (185, 'Red lava crab', 'Moldovan', '11.02.2012');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (186, 'Macaw, red and blue', 'Croatian', '03.05.1968');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (187, 'Legaan, water', 'West Frisian', '08.03.2005');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (188, 'Ovenbird', 'Indonesian', '06.01.1957');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (189, 'Red-necked phalarope', 'Amharic', '04.08.1985');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (190, 'Mexican boa', 'Bislama', '06.03.2009');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (191, 'Dolphin, common', 'Pashto', '16.08.2015');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (192, 'Vervet monkey', 'Belarusian', '07.02.1968');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (193, 'Common raccoon', 'Hungarian', '23.09.2012');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (194, 'Vulture, turkey', 'Belarusian', '05.06.1967');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (195, 'Deer, swamp', 'Romanian', '04.07.1954');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (196, 'Shrike, southern white-crowned', 'Indonesian', '12.12.1979');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (197, 'Lappet-faced vulture', 'Papiamento', '04.10.1967');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (198, 'Beaver, european', 'Sotho', '17.06.1965');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (199, 'Raccoon dog', 'Belarusian', '23.02.2002');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (200, 'Nutcracker, clark''s', 'Haitian Creole', '28.08.2017');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (201, 'Possum, western pygmy', 'Aymara', '23.11.1958');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (202, 'Racer, blue', 'Swati', '26.11.1968');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (203, 'Tokay gecko', 'Afrikaans', '27.06.1997');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (204, 'Owl, snowy', 'German', '01.04.1965');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (205, 'Lion, asian', 'Yiddish', '28.03.1971');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (206, 'Bennett''s wallaby', 'English', '10.05.1964');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (207, 'Ibis, puna', 'Malay', '01.04.1991');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (208, 'Possum, western pygmy', 'Danish', '03.01.2013');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (209, 'Savannah deer (unidentified)', 'West Frisian', '25.06.2007');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (210, 'Dusky gull', 'New Zealand Sign Language', '11.01.1997');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (211, 'Short-nosed bandicoot', 'Tamil', '19.12.1997');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (212, 'Greater blue-eared starling', 'Arabic', '27.04.1967');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (213, 'Black-footed ferret', 'Mongolian', '27.08.1971');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (214, 'Hyrax', 'French', '25.11.1959');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (215, 'Flamingo, greater', 'Georgian', '19.03.1986');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (216, 'Fat-tailed dunnart', 'Kannada', '18.09.1960');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (217, 'Antechinus, brown', 'Bosnian', '13.06.1992');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (218, 'African bush squirrel', 'Khmer', '28.06.1975');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (219, 'Nutcracker, clark''s', 'Czech', '13.03.1970');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (220, 'Weaver, sociable', 'Afrikaans', '22.10.2017');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (221, 'Striped dolphin', 'Arabic', '17.03.2000');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (222, 'Tortoise, galapagos', 'Bislama', '04.04.1953');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (223, 'Grouse, sage', 'Gagauz', '30.11.1973');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (224, 'Indian porcupine', 'New Zealand Sign Language', '20.10.1994');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (225, 'Golden-mantled ground squirrel', 'Greek', '21.05.2009');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (226, 'Magnificent frigate bird', 'Moldovan', '11.12.1983');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (227, 'Wombat, southern hairy-nosed', 'Gujarati', '10.11.1961');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (228, 'Black-cheeked waxbill', 'Macedonian', '24.08.1958');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (229, 'Macaque, pig-tailed', 'Croatian', '24.05.2001');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (230, 'Striped dolphin', 'Assamese', '12.01.1986');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (231, 'Francolin, swainson''s', 'Portuguese', '23.02.1959');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (232, 'Harbor seal', 'Albanian', '12.08.1983');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (233, 'Lion, steller sea', 'Estonian', '01.01.1992');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (234, 'Galapagos dove', 'Thai', '09.01.2002');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (235, 'Greater sage grouse', 'Bislama', '02.07.1962');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (236, 'Red-tailed hawk', 'Chinese', '11.06.1973');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (237, 'African clawless otter', 'Swati', '29.05.1964');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (238, 'Arctic hare', 'Azeri', '25.09.1975');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (239, 'Secretary bird', 'Thai', '02.02.1993');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (240, 'Malagasy ground boa', 'Belarusian', '27.12.1992');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (241, 'Fox, blue', 'Croatian', '09.02.1956');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (242, 'Bird, black-throated butcher', 'Chinese', '01.07.1996');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (243, 'Fox, arctic', 'Yiddish', '22.10.2012');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (244, 'Blue catfish', 'Icelandic', '15.08.1974');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (245, 'Kongoni', 'Italian', '11.02.2012');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (246, 'Kangaroo, jungle', 'Moldovan', '02.09.1960');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (247, 'Butterfly, tropical buckeye', 'Malayalam', '06.01.1996');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (248, 'Violet-eared waxbill', 'Montenegrin', '11.04.1972');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (249, 'Russian dragonfly', 'Dhivehi', '07.04.1989');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (250, 'Eagle owl (unidentified)', 'Tsonga', '26.04.2002');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (251, 'Tapir, brazilian', 'Amharic', '25.02.1978');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (252, 'Smith''s bush squirrel', 'Kashmiri', '01.09.1969');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (253, 'Galapagos penguin', 'Kannada', '30.11.2000');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (254, 'Mongoose, yellow', 'Romanian', '29.08.1957');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (255, 'Ring-tailed lemur', 'Burmese', '29.10.2008');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (256, 'Margay', 'Hiri Motu', '27.10.1973');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (257, 'Silver-backed jackal', 'Tsonga', '24.03.1958');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (258, 'Fox, savanna', 'Chinese', '09.12.1979');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (259, 'Mongoose, javan gold-spotted', 'Marathi', '15.07.1979');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (260, 'Hawk, galapagos', 'Swati', '25.12.1983');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (261, 'Albatross, galapagos', 'Maltese', '23.07.1966');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (262, 'Thrasher, curve-billed', 'Kannada', '20.09.2016');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (263, 'Bandicoot, short-nosed', 'Polish', '08.05.1961');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (264, 'Pied butcher bird', 'Hiri Motu', '29.09.1977');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (265, 'Black-tailed tree creeper', 'Spanish', '07.02.1992');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (266, 'Gecko, barking', 'French', '28.05.2005');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (267, 'Wood pigeon', 'Pashto', '26.08.1978');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (268, 'Suricate', 'Afrikaans', '01.11.1950');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (269, 'Otter, small-clawed', 'Catalan', '17.08.1950');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (270, 'Brindled gnu', 'West Frisian', '11.10.2007');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (271, 'Mongoose, eastern dwarf', 'Icelandic', '18.07.1958');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (272, 'Crowned eagle', 'Burmese', '16.01.1982');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (273, 'Gulls (unidentified)', 'Albanian', '09.08.1973');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (274, 'Black-footed ferret', 'Korean', '06.05.1978');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (275, 'Tortoise, radiated', 'Lithuanian', '18.07.1975');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (276, 'Mongoose, yellow', 'Indonesian', '29.09.1953');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (277, 'Paddy heron (unidentified)', 'Danish', '30.01.1978');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (278, 'Shrike, southern white-crowned', 'Yiddish', '02.08.1973');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (279, 'Stork, jabiru', 'Haitian Creole', '19.01.2011');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (280, 'Tyrant flycatcher', 'Azeri', '02.03.1968');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (281, 'Royal tern', 'Dhivehi', '19.04.1989');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (282, 'Sea birds (unidentified)', 'Ndebele', '24.08.1967');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (283, 'Goldeneye, common', 'Croatian', '29.07.2001');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (284, 'Dolphin, bottle-nose', 'Belarusian', '05.02.1969');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (285, 'Starling, greater blue-eared', 'Bulgarian', '07.03.1965');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (286, 'Rattlesnake, eastern diamondback', 'Thai', '15.12.1978');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (287, 'Mandras tree shrew', 'Hebrew', '14.07.2016');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (288, 'Lizard, blue-tongued', 'Hiri Motu', '02.11.1994');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (289, 'Jabiru stork', 'Malay', '09.11.1951');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (290, 'Tortoise, desert', 'Sotho', '30.04.2010');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (291, 'Tammar wallaby', 'Greek', '21.08.2011');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (292, 'Azara''s zorro', 'Persian', '18.08.2009');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (293, 'Ibex', 'Bengali', '16.07.2012');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (294, 'Fox, grey', 'Tok Pisin', '22.04.1978');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (295, 'Corella, long-billed', 'Gujarati', '08.07.1975');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (296, 'Savannah deer', 'German', '11.01.2015');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (297, 'Cat, long-tailed spotted', 'Sotho', '03.12.1973');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (298, 'Coatimundi, white-nosed', 'Guaraní', '06.02.2010');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (299, 'Screamer, crested', 'Persian', '09.10.1976');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (300, 'Four-spotted skimmer', 'Fijian', '07.04.1972');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (301, 'Corella, long-billed', 'Filipino', '04.12.1963');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (302, 'Crowned eagle', 'Albanian', '04.07.1957');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (303, 'African jacana', 'Afrikaans', '14.09.1954');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (304, 'Duck, blue', 'Quechua', '20.08.1999');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (305, 'Waxbill, blue', 'Gagauz', '06.11.1989');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (306, 'Monkey, black spider', 'Danish', '14.12.2010');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (307, 'Otter, brazilian', 'Spanish', '03.01.1958');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (308, 'Stork, yellow-billed', 'Tsonga', '18.02.2006');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (309, 'Madagascar hawk owl', 'Danish', '04.07.1963');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (310, 'Ring-tailed lemur', 'West Frisian', '01.07.1988');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (311, 'Western patch-nosed snake', 'Dutch', '19.03.1957');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (312, 'Dragon, frilled', 'Persian', '29.08.1995');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (313, 'Neotropic cormorant', 'Irish Gaelic', '02.02.1967');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (314, 'Kaffir cat', 'Māori', '13.02.1976');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (315, 'Bear, black', 'Maltese', '26.01.2000');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (316, 'Elk, Wapiti', 'Hiri Motu', '19.05.2013');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (317, 'Black-winged stilt', 'Tsonga', '04.10.2010');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (318, 'Monkey, black spider', 'Pashto', '21.06.2013');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (319, 'Jackal, indian', 'Kazakh', '10.12.1977');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (320, 'Crested bunting', 'Latvian', '06.03.2012');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (321, 'Long-tailed spotted cat', 'Marathi', '25.11.2008');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (322, 'Brush-tailed bettong', 'Armenian', '03.07.1959');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (323, 'Sloth, pale-throated three-toed', 'Luxembourgish', '20.02.2015');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (324, 'Dragon, western bearded', 'Norwegian', '02.11.1968');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (325, 'Coot, red-knobbed', 'Punjabi', '30.12.1990');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (326, 'Potoroo', 'Polish', '04.05.1979');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (327, 'Pintail, white-cheeked', 'Kashmiri', '26.09.1964');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (328, 'Thirteen-lined squirrel', 'Tok Pisin', '06.08.1958');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (329, 'American black bear', 'Spanish', '05.04.1979');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (330, 'Dusky rattlesnake', 'Gujarati', '29.03.2003');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (331, 'Canadian river otter', 'Japanese', '10.12.2017');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (332, 'Plover, three-banded', 'Kazakh', '21.09.1995');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (333, 'Prehensile-tailed porcupine', 'New Zealand Sign Language', '08.11.1997');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (334, 'Baboon, chacma', 'West Frisian', '21.09.2002');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (335, 'Greater flamingo', 'German', '09.01.1984');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (336, 'Dolphin, common', 'Malayalam', '15.07.2005');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (337, 'Mudskipper (unidentified)', 'Arabic', '22.07.1982');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (338, 'Peregrine falcon', 'Khmer', '04.05.1970');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (339, 'Rhinoceros, white', 'Spanish', '03.04.1982');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (340, 'Wallaby, red-necked', 'Montenegrin', '06.08.2013');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (341, 'Langur, gray', 'Korean', '20.04.1970');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (342, 'Black-winged stilt', 'Burmese', '15.03.1990');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (343, 'Meerkat', 'German', '02.12.1988');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (344, 'Wagtail, african pied', 'Bengali', '07.08.2015');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (345, 'Pacific gull', 'Hebrew', '09.07.1989');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (346, 'Common ringtail', 'Zulu', '31.10.2003');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (347, 'Penguin, magellanic', 'Telugu', '24.08.1951');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (348, 'Dog, raccoon', 'Telugu', '05.10.1982');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (349, 'Tern, white-winged', 'Persian', '08.10.2010');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (350, 'Indian tree pie', 'Tok Pisin', '15.12.1993');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (351, 'Giant otter', 'Swati', '25.11.2011');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (352, 'Black-backed magpie', 'Hiri Motu', '26.04.1979');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (353, 'Grey fox', 'Montenegrin', '04.11.1961');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (354, 'Marabou stork', 'Polish', '11.08.1966');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (355, 'Common langur', 'Dari', '14.11.2000');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (356, 'Square-lipped rhinoceros', 'Portuguese', '10.09.1971');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (357, 'Fox, blue', 'Amharic', '12.02.1998');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (358, 'Goose, spur-winged', 'Spanish', '24.02.2004');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (359, 'Screamer, southern', 'Bislama', '28.12.1967');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (360, 'Musk ox', 'Swahili', '06.01.1987');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (361, 'Phalarope, northern', 'Punjabi', '23.10.1964');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (362, 'Anteater, giant', 'Moldovan', '20.01.1995');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (363, 'Duck, mountain', 'Dhivehi', '08.08.1956');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (364, 'Green-winged trumpeter', 'Bislama', '12.02.1965');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (365, 'Black-crowned night heron', 'Mongolian', '21.05.2010');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (366, 'Stork, painted', 'Chinese', '23.10.2004');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (367, 'Swan, black', 'Swahili', '04.09.1982');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (368, 'Cat, kaffir', 'French', '20.02.1965');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (369, 'Sandhill crane', 'Filipino', '09.02.1990');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (370, 'Madagascar hawk owl', 'Pashto', '13.06.1986');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (371, 'Two-toed sloth', 'Tajik', '11.03.1983');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (372, 'Zebra, plains', 'Fijian', '29.07.1954');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (373, 'Crab-eating fox', 'Tajik', '21.04.1980');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (374, 'Admiral, indian red', 'Bislama', '29.04.1953');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (375, 'Boa, malagasy ground', 'Bengali', '24.11.1999');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (376, 'Lory, rainbow', 'Ndebele', '25.11.2009');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (377, 'Ringtail', 'Tswana', '30.09.1981');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (378, 'Blackbuck', 'Malayalam', '25.01.2010');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (379, 'Mexican beaded lizard', 'Norwegian', '13.06.1953');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (380, 'Lemur, ring-tailed', 'Afrikaans', '16.09.1977');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (381, 'Lion, steller sea', 'Kurdish', '09.09.2014');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (382, 'Baleen whale', 'Zulu', '30.03.1987');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (383, 'Short-beaked echidna', 'Bislama', '14.09.1955');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (384, 'Wallaroo, common', 'Tok Pisin', '02.03.2016');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (385, 'Cougar', 'Latvian', '15.04.1990');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (386, 'Dragon, asian water', 'Italian', '09.05.1981');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (387, 'Barbet, black-collared', 'Tswana', '25.08.1959');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (388, 'Monitor, white-throated', 'Amharic', '23.07.1962');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (389, 'Squirrel, european red', 'Gagauz', '12.01.2002');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (390, 'Waxbill, violet-eared', 'Moldovan', '13.10.2002');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (391, 'Crown of thorns starfish', 'Persian', '01.04.1989');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (392, 'Jackal, indian', 'Albanian', '14.09.1982');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (393, 'Silver-backed jackal', 'Greek', '05.10.1966');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (394, 'Falcon, prairie', 'Bengali', '25.11.1995');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (395, 'Seven-banded armadillo', 'Sotho', '29.07.2011');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (396, 'Common eland', 'French', '30.04.1982');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (397, 'Brocket, red', 'Icelandic', '16.10.1988');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (398, 'Beaver, north american', 'Persian', '22.11.1977');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (399, 'Paddy heron (unidentified)', 'Maltese', '27.03.1992');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (400, 'Little heron', 'Khmer', '25.03.2016');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (401, 'Ground monitor (unidentified)', 'Thai', '07.06.1958');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (402, 'Sally lightfoot crab', 'West Frisian', '25.01.1952');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (403, 'Neotropic cormorant', 'Hebrew', '16.01.2018');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (404, 'Dog, bush', 'Chinese', '15.03.1985');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (405, 'Blue duck', 'Somali', '25.11.2015');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (406, 'Smith''s bush squirrel', 'Persian', '17.01.2018');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (407, 'Llama', 'Kashmiri', '15.09.1963');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (408, 'Genet, common', 'Thai', '05.04.1952');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (409, 'Phalarope, northern', 'Zulu', '14.10.1959');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (410, 'Small-clawed otter', 'Hindi', '20.04.2003');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (411, 'Puma', 'Dutch', '24.12.2002');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (412, 'Screamer, southern', 'Bosnian', '10.05.1964');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (413, 'Klipspringer', 'Somali', '09.02.1959');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (414, 'Eastern boa constrictor', 'Amharic', '24.10.1992');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (415, 'Stork, white', 'Latvian', '21.03.2015');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (416, 'Salmon pink bird eater tarantula', 'Lithuanian', '29.06.2007');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (417, 'Lynx, african', 'German', '13.06.2015');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (418, 'Manatee', 'Papiamento', '11.02.1963');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (419, 'Rat, desert kangaroo', 'Burmese', '12.08.1990');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (420, 'Pie, rufous tree', 'Spanish', '20.05.1966');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (421, 'Impala', 'Dutch', '23.08.1957');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (422, 'Egyptian vulture', 'Burmese', '19.08.2007');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (423, 'Asian water dragon', 'Latvian', '08.10.1963');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (424, 'White-winged tern', 'Yiddish', '29.03.1987');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (425, 'Squirrel, thirteen-lined', 'Khmer', '18.09.2009');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (426, 'Black swan', 'Thai', '26.03.1961');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (427, 'Snake, carpet', 'Azeri', '18.09.2015');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (428, 'Vicuna', 'Assamese', '23.03.1964');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (429, 'Owl, australian masked', 'Khmer', '22.03.1974');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (430, 'Lesser masked weaver', 'Kurdish', '28.01.2002');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (431, 'Civet, common palm', 'Dutch', '18.02.1961');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (432, 'Macaw, blue and gold', 'Tsonga', '14.04.1972');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (433, 'Madagascar fruit bat', 'Malay', '05.01.1980');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (434, 'Squirrel, malabar', 'Albanian', '19.10.2003');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (435, 'Armadillo, giant', 'Hebrew', '28.11.2000');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (436, 'Puna ibis', 'Nepali', '30.01.1984');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (437, 'African wild dog', 'Māori', '11.05.1954');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (438, 'Snake, eastern indigo', 'Hebrew', '02.09.1980');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (439, 'Starling, greater blue-eared', 'Dari', '03.07.1997');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (440, 'Brown lemur', 'Dhivehi', '01.09.1981');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (441, 'Guanaco', 'Chinese', '25.02.1994');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (442, 'Cobra, egyptian', 'Nepali', '18.08.1956');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (443, 'Porcupine, crested', 'Bulgarian', '25.10.1958');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (444, 'Crane, blue', 'Azeri', '01.08.2017');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (445, 'Gnu, brindled', 'Hebrew', '17.09.1950');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (446, 'Capuchin, weeper', 'Khmer', '28.07.1970');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (447, 'North American beaver', 'Swedish', '06.10.1995');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (448, 'Lynx, african', 'Persian', '15.09.1984');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (449, 'Anteater, giant', 'Hungarian', '06.07.2004');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (450, 'Rat, desert kangaroo', 'Sotho', '11.11.1966');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (451, 'Musk ox', 'Icelandic', '21.12.2011');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (452, 'Nighthawk, common', 'Amharic', '22.09.2015');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (453, 'Pale white-eye', 'Tswana', '08.02.1964');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (454, 'Drongo, fork-tailed', 'Indonesian', '08.07.1963');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (455, 'Plover, three-banded', 'Māori', '03.02.2003');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (456, 'Kaffir cat', 'New Zealand Sign Language', '30.10.1977');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (457, 'Square-lipped rhinoceros', 'Lithuanian', '06.11.1961');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (458, 'Francolin, coqui', 'Dari', '28.01.1960');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (459, 'Eastern grey kangaroo', 'Greek', '06.06.2010');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (460, 'Squirrel, nelson ground', 'Tamil', '26.03.2006');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (461, 'Brown pelican', 'Kannada', '01.03.1969');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (462, 'Lemming, arctic', 'Tajik', '07.08.1965');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (463, 'Boa, malagasy ground', 'Persian', '24.10.1973');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (464, 'Squirrel, palm', 'Hungarian', '11.02.2000');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (465, 'Baboon, chacma', 'Quechua', '02.12.1989');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (466, 'Tammar wallaby', 'Tamil', '27.07.1971');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (467, 'Musk ox', 'Croatian', '25.01.1980');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (468, 'Nile crocodile', 'Haitian Creole', '15.12.1975');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (469, 'Egyptian viper', 'Croatian', '03.12.2017');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (470, 'Nyala', 'Bosnian', '30.12.1978');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (471, 'Yellow-throated sandgrouse', 'Kurdish', '05.06.1982');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (472, 'Common seal', 'Sotho', '18.04.2008');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (473, 'Skimmer, four-spotted', 'Irish Gaelic', '08.09.1981');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (474, 'Yellow-brown sungazer', 'Thai', '09.11.2000');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (475, 'Civet, small-toothed palm', 'Kazakh', '08.03.2018');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (476, 'American beaver', 'Croatian', '06.12.2015');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (477, 'African lion', 'Oriya', '04.05.1975');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (478, 'Deer, savannah', 'Georgian', '23.06.1968');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (479, 'Blue duck', 'Filipino', '15.04.2003');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (480, 'Blue catfish', 'Zulu', '20.12.1960');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (481, 'Pie, indian tree', 'Telugu', '20.08.1973');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (482, 'Goose, andean', 'Zulu', '25.04.1979');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (483, 'Darwin ground finch (unidentified)', 'Malayalam', '10.03.2009');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (484, 'Tinamou, elegant crested', 'Norwegian', '26.10.2000');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (485, 'Brazilian tapir', 'Albanian', '21.06.1970');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (486, 'Heron, yellow-crowned night', 'Swati', '30.04.1953');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (487, 'Javan gold-spotted mongoose', 'Burmese', '23.09.1987');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (488, 'Tortoise, asian foreset', 'Malay', '15.04.1981');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (489, 'Cat, native', 'Danish', '20.11.1970');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (490, 'Bee-eater, white-fronted', 'Mongolian', '11.08.2009');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (491, 'Blacksmith plover', 'Dutch', '24.05.1959');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (492, 'Azara''s zorro', 'Bosnian', '07.03.1983');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (493, 'Carmine bee-eater', 'Azeri', '02.08.1956');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (494, 'African polecat', 'Somali', '11.08.1997');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (495, 'Eastern grey kangaroo', 'Amharic', '29.06.1961');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (496, 'Asian water buffalo', 'Pashto', '31.12.2006');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (497, 'Black-tailed tree creeper', 'Malagasy', '06.07.1989');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (498, 'Mountain duck', 'Gagauz', '16.03.1996');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (499, 'Possum, common brushtail', 'Tajik', '16.01.1972');
insert into Banda (cod_banda, nome_banda, nacionalidade_banda, data_fundacao_banda) values (500, 'Squirrel, eurasian red', 'Dhivehi', '28.11.1997');
